### ISSUE TITLE
Can not compile cpclib-disc

### ISSUE THREAD

**Issue by orousseil** [cpcsdk/rust.cpclib#7]
Hello,

When calling `cargo build` in cpclib-disc directory, I got this errors :

```
error[E0557]: feature has been removed
 --> cpclib-disc/src/lib.rs:1:12
  |
1 | #![feature(register_attr)]
  |            ^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![register_tool]`

error: cannot find attribute `register_attr` in this scope
 --> cpclib-disc/src/lib.rs:2:4
  |
2 | #![register_attr(get)]
  |    ^^^^^^^^^^^^^ help: a built-in attribute with a similar name exists: `register_tool`
```

**Comment by rgiot** [comment]
Hello; are you using a nightly compiler ?
I can dig during next week end. Ping me if I forget

**Comment by orousseil** [comment]
I'm on linux (debian 10)

```
#cargo --version         
cargo 1.66.0-nightly (73ba3f35e 2022-09-18)
```

```
#clang --version
clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

other modules like `cpclib-sna`or `cpclib-tokens` compile.

**Comment by orousseil** [comment]
I just have try on a more recent ubuntu 22.04 (with clang 14)

And it give me the same error (feature has been removed)

nb : for documentation you could add in prerequisite to install libssl-dev with :
`sudo apt install libssl-dev`
otherwise openssl can't compile

**Comment by rgiot** [comment]
Hello last commit #d9a062a1d66c37b843bdf93f0d9c8105dce08c2d should fix the issue.

Please note that I'm not confident of the cpclib-disc crate implementation. For my latest demo https://www.pouet.net/prod.php?which=88554 I quickly stopped to use it to rely on already existing tools as I had too many bugs. I do not remember if I have updated the crate since
